version: 2
updates:
  # Maintain dependencies for cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "hainish"
    commit-message:
      prefix: "cargo-update"
    labels:
      - "dependencies"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "hainish"
    versioning-strategy: auto
